<!-- <!doctype html> -->
<!-- <html lang="en"> -->
    <!-- <head> -->
        <!-- Required meta tags -->
        <!-- <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->

        <!-- Bootstrap CSS -->

        <!-- <link  rel="stylesheet" type="text/css" href="<?= $this->access('asset/css/site.css') ?>" >
        <link  rel="stylesheet" type="text/css" href="<?= $this->access('asset/css/bootstrap.min.css') ?>" >

        <title>| <?= $this->title ?></title>
    </head> -->
<!-- 
    <body>
        <div class="container-fluid"> -->

            <!-- Page Header -->
            <!-- <div class="row px-1 py-1 top"  id="top" >
                <div class="top-link col-sm-8 col-md-3" id="top-link">
                    <a href="#" class="top-nav-item">About</a>
                    <a href="#" class="top-nav-item">Advertise</a>
                    <a href="#" class="top-nav-item">Privacy & Policy</a>
                    <a href="#" class="top-nav-item">Contact</a>
                </div> -->
                <!-- <div class="offset-md-5"></div> -->
                <!-- <div class="col-md-3 offset-md-6">
                    <div class="row">
                        <div class="offset-md-2"></div>
                        <div class="date col-md-7" id="date"><?php echo date("Y/m/d")?></div>
                        <div class="login col-md-3 pl-3" id="login"><a href="<?= $this->path('adm.logout') ?>"> <span class=" fa fa-lock" id="login-icon"></span> Login </a></div>
                    </div>
                </div>
            </div> -->
            <!--  **************** End of Page Header ************************* -->

            <!-- Page Content Here -->
            <!-- <div class="container" >
                 <?= $content; ?>
            </div> -->
            <!--  **************** End of Page Content ************************* -->

         

        <!-- <script src="<?= $this->access('asset/js/jquery.min.js') ?>"></script> -->
        <!-- <script src="<?= $this->access('asset/js/bootstrap.min.js') ?>"></script>
    </body> -->





<!-- </html> -->