<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image" href="<?=$this->access('asset/img/jobhouse-w.png')?>">
    <title>Login</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Arial:300,400,500,700&display=swap">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?=$this->access('asset/css/fontawesome.min.css')?>">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="<?=$this->access('asset/css/bootstrap.min.css')?>" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Material Design Bootstrap -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">

    <link href="<?= $this->access('asset/css/mdb.min.css')?>" rel="stylesheet"/> 
    <!-- Your custom styles (optional) -->
    <link href="<?=$this->access('asset/css/base.css')?>" rel="stylesheet"/>
</head>

<body class="login-back">

    <!-- Start your project here-->
    <div class="card fl-login-card">
        <div class="card-body">
            <div class="md-form">
                <p class="font-weight-light"></p>

                <!-- Default form login -->
                <form class="text-center needs-validation" method="post" novalidate>
                    <!-- Username -->
                    <div class="md-form input-with-pre-icon">
                        <div>
                            <i style="color:" class="fas fa-user input-prefix"></i>
                            <input type="text" class="form-control" placeholder="Username" required/>
                        </div>
                        <div class="invalid-feedback">Please enter username</div>
                    </div>

                    <!-- Password -->
                    <div class="md-form input-with-pre-icon">
                        <div>
                            <i class="fa fa-lock input-prefix" aria-hidden="true"></i>
                            <input type="password" class="form-control mb-4" placeholde="password" required/>
                            <!-- <label for="userPassword"></label> -->
                        </div>
                        <div class="invalid-feedback">Please enter password</div>

                    </div>


                    <div class="justify-content-around remember">

                        <!-- Remember me -->
                        <div class=" custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                            <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
                        </div>

                        <div class="forgot">
                            <!-- Forgot password -->
                            <a href="#forgot-password" id="forgot" class="text-primary">Forgot password?</a>
                        </div>
                    </div>

                    <!-- Sign in button -->
                    <div class="login-bottom">
                        <input class="btn fl-btn-pm btn-rounded btn-block my-4" type="submit" value="LOGIN">

                        <!-- Register -->
                        <p>Not a member?
                            <a href="<?= $this->path('site.register')?>">Register</a>
                        </p>
                        <!-- Social login -->
                        <p>Sign in with Google: <a href="#" class="mx-2" role="button"><i class="fab fa-google light-blue-text"></i></a>
                        </p>
                    </div>

                </form>
                <!-- Default form login -->
            </div>
            <!--forgot password form-->




        <!-- End your project here-->
    <!-- jQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/js/mdb.min.js"></script>
    <!-- Your custom scripts (optional) -->
    <script src="<?=$this->access('asset/js/customscripts.js')?>" type="text/javascript"></script>
    <!-- jQuery -->
    <script type="text/javascript" src="<?=$this->access('asset/js/jquery.min.js')?>"> </script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?=$this->access('asset/js/popper.min.js')?>"> </script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?=$this->access('asset/js/bootstrap.min.js')?>"> </script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?=$this->access('assetjs/mdb.min.js')?>"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript" src="<?=$this->access('asset/js/customscripts.js')?>"></script>

</body>

</html>
