<!DOCTYPE html>
<html  lang="en">

<head>

<style>
    html:{
        height: 100%;
        overflow: hidden;
    }
    </style>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Freelancer DashBoard</title>

  <!-- Custom fonts for this template-->
 <!-- Custom fonts for this template-->
  <link href="<?=$this->access('asset/form/vendor/fontawesome-free/css/all.min.css')?>" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="<?=$this->access('asset/form/css/sb-admin-2.min.css')?>" rel="stylesheet">
  <link rel="stylesheet" href="<?=$this->access('asset/css/style.csss')?>">
    <link rel="stylesheet" href="<?=$this->access('asset/css/countrySelect.min.cs')?>">


</head>

<body class="bg-gradient-primary">
  
  <!-- Page Wrapper -->
  <div id="wrapper">
   <!-- End of Sidebar -->
    <!-- Main Content -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <div id="content">

        <!-- Topbar -->
        <nav style="background-color:#207b41;" class="navbar navbar-expand navbar-light fixed topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          

        
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-white-600 small">Clement Koomson<!--User's full name comes here--></span>
                <img class="img-profile rounded-circle" src=""><!--User's profile picture comes here-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="">   
              
                <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">
          

        <div class="container">

<div style="margin-left: 200px;" class="card o-hidden border-0 shadow-lg my-5 w-75">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class=" col big-box">
        <div class=" p-5">
          <div class="text-center">
            <h1 class="h4 text-gray-900 mb-4">Complete your profile</h1>
          </div>
          <form class="user" method="post">
          <div class="form-group row">
              <div class="col-sm-6 mb-3 mb-sm-0">
              <input type="text" name="title" class="form-control"  placeholder="Name" readonly>
              </div>
              <div class="col-sm-6">
              <input type="text" name="title" class="form-control" placeholder="Email" readonly>
              </div>
            </div>
              
              
            <div class="form-group row">
              <div class="col-sm-6 mb-3 mb-sm-0">
    
            <input class="form-control" type="text" name="" id="country_selectors" style="display: none;">
              <input type="text" name="country" class="form-control" placeholder="Country">
              </div>
              <div class="col-sm-6">
              <input type="text" name="city" class="form-control" placeholder="City">
              </div>
            </div>
            <div class="form-group">
            <input type="text" name="address" class="form-control" placeholder="Address">
            </div>
            <div class="form-group">
            <input type="text" name="links" class="form-control" placeholder="Links to projects">
            </div>
              <div class="form-group">
              <textarea class="form-control" name="summary" placeholder="Profile Summary"></textarea>
              </div>

              <div class="form-group">
              <input id="imageUpload" type="file" name="profile_photo" placeholder="Photo" required="" capture>
              <br/>
            <input  style="width:400px;background-color: #207b41;border-color:#207b41;" type="submit" class="btn btn-primary btn-user btn-block" value="Save Profile">

              </form>

        </div>
      </div>
    </div>
  </div>
</div>

</div>


      </div>
      <!-- End of Main Content -->
           <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>AmaliTech Freelance 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
 
    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

   
        <!-- Bootstrap core JavaScript-->
  <script src="<?=$this->access('asset/form/vendor/jquery/jquery.min.js')?> "></script>
  <script src="<?=$this->access('asset/form/vendor/bootstrap/js/bootstrap.bundle.min.js')?>"></script>

  <!-- Core plugin JavaScript-->
  <script src="<?=$this->access('asset/vendor/jquery-easing/jquery.easing.min.js')?>"></script>

  <!-- Custom scripts for all pages-->
  <script src="<?=$this->access('asset/form/js/sb-admin-2.min.js')?>"></script>
  <script src="<?=$this->access('asset/form/js/sb-admin-2.min.js')?>"></script>
  <script src="<?=$this->access('asset/js/customscripts.js')?>"></script>
  <script src="<?=$this->access('asset/js/addons/datatables-select.min.jss')?>"></script>
  <script src="<?=$this->access('asset/js/phonecode.jss')?>"></script>

</body>

</html>
